<a href="https://colab.research.google.com/github/yukinaga/image_generation/blob/main/section_2/02_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor
TensorはPyTorchにおいて最も基本となるデータ構造です。  
今回は、Tensorを生成したり、Tensor同士の計算をしたりするコードを練習します。

## Tensorの生成
torchのtensor関数によりTensorを生成します。  
以下のセルではPythonのリストからTensorを生成します。  
また、type( )により型を確認します。  

In [1]:
import torch

a = torch.tensor([1,2,3])
print(a, type(a))

tensor([1, 2, 3]) <class 'torch.Tensor'>


他にも、様々な方法でTensorを生成することができます。

In [2]:
# 2重のリストから生成
b = torch.tensor([[1, 2],
                  [3, 4]])
print(b)

# dypeを指定し、倍精度のTensorにする
c = torch.tensor([[1, 2],
                  [3, 4]], dtype=torch.float64)
print(c)

# 0から9までの数値で初期化
d = torch.arange(0, 10)
print(d)

# すべての値が0の、2×3のTensor
e = torch.zeros(2, 3)
print(e)

# すべての値が乱数の、2×3のTensor
f = torch.rand(2, 3)
print(f)

# Tensorの形状はsizeメソッドで取得
print(f.size())

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.8891, 0.7611, 0.2630],
        [0.2065, 0.5270, 0.8960]])
torch.Size([2, 3])


## TensorとNumPyの配列の変換
numpy()メソッドでTensorをNumPyの配列に変換することができます。  
また、from_numpy( )関数でNumPyの配列をTensorに変換することができます。

In [3]:
# Tensor → NumPy
a = torch.tensor([[1, 2],
                  [3, 4.]])
b = a.numpy()
print(b)

# NumPy → Tensor
c = torch.from_numpy(b)
print(c)

[[1. 2.]
 [3. 4.]]
tensor([[1., 2.],
        [3., 4.]])


## 範囲を指定してアクセス
様々な方法で、Tensorの要素に範囲を指定してアクセスすることができます。

In [4]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

# 2つのインデックスを指定
print(a[0, 1])

# 範囲を指定
print(a[1:2, :2])

# リストで複数のインデックスを指定
print(a[:, [0, 2]])

# 3より大きい要素のみを指定
print(a[a>3])

# 要素の変更
a[0, 2] = 11
print(a)

# 要素の一括変更
a[:, 1] = 22
print(a)

# 10より大きい要素のみ変更
a[a>10] = 33
print(a)

tensor(2)
tensor([[4, 5]])
tensor([[1, 3],
        [4, 6]])
tensor([4, 5, 6])
tensor([[ 1,  2, 11],
        [ 4,  5,  6]])
tensor([[ 1, 22, 11],
        [ 4, 22,  6]])
tensor([[ 1, 33, 33],
        [ 4, 33,  6]])


## Tensorの演算
Tensorによりベクトルや行列を表現することができます。  
これらの演算は、一定のルールに基づき行われます。  

In [5]:
# ベクトル
a = torch.tensor([1, 2, 3]) 
b = torch.tensor([4, 5, 6])

# 行列
c = torch.tensor([[6, 5, 4],
                  [3, 2, 1]])

# ベクトルとスカラーの演算
print(a + 3)

# ベクトル同士の演算
print(a + b) 

# 行列とスカラーの演算
print(c + 2)

# 行列とベクトルの演算（ブロードキャスト）
print(c + a)

# 行列同士の演算
print(c + c)

tensor([4, 5, 6])
tensor([5, 7, 9])
tensor([[8, 7, 6],
        [5, 4, 3]])
tensor([[7, 7, 7],
        [4, 4, 4]])
tensor([[12, 10,  8],
        [ 6,  4,  2]])


## 様々な値の計算
平均値、合計値、最大値、最小値など様々な値を計算する関数とメソッドが用意されています。


In [6]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6.]])

# 平均値を求める関数
m = torch.mean(a)
print(m.item())  # item()で値を取り出す

# 平均値を求めるメソッド
m = a.mean()
print(m.item())

# 列ごとの平均値
print(a.mean(0))

# 合計値
print(torch.sum(a).item())

# 最大値
print(torch.max(a).item())

# 最小値
print(torch.min(a).item())

3.5
3.5
tensor([2.5000, 3.5000, 4.5000])
21.0
6.0
1.0
